[package]
name = "blogmake"
version = "0.1.0"
edition = "2021"

[dependencies]
markdown = { path = "/home/tomgilligan257/markdown-rs" }
markup = "0.13.1"
serde = { version = "1.0", features = [ "derive" ] }
serde_yaml = ">= 0.9"
toml = ">= 0.7.6"
svg = "0.13.1"

[build-dependencies]
markup = "0.13.1"
