[package]
name = "blog"
version = "0.1.0"
edition = "2021"

[dependencies]
markdown = "1.0.0-alpha.11"
markup = "0.13.1"
serde = { version = "1.0", features = [ "derive" ] }
serde_yaml = ">= 0.9"
toml = ">= 0.7.6"
syntect = "5.0.0"
thirtyfour = "0.32.0-rc.8"
tokio = "1.29.1"
hyper-staticfile = "0.9.5"
hyper = { version = "0.14.27", features = [ "server" ] }
rss = "2"
chrono = "0.4.26"
