[alias]
xtask = "run --package xtask --"
crawl = "run --bin crawl --"
generate = "run --bin generate --"
screenshot = "run --bin screenshot --"
serve = "run --bin serve --"
visual_diff = "run --bin visual_diff --"
watch = "run --bin watch --"
