name: Check for Unused Dependencies
on:
  workflow_dispatch
jobs:
  dependencies:
    name: Dependencies
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - run: cargo install cargo-udeps
    - run: cargo udeps
