name: CI
on:
- push
concurrency:
  group: ${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}
  cancel-in-progress: true
env:
  CARGO_TERM_COLOR: always
  DISPLAY: :99
  RUST_BACKTRACE: 1
  LANGUAGE: en_AU
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-rust-${{ hashFiles('**/Cargo.toml') }}
    - run: cargo xtask ci
  generate:
    needs:
    - ci
    name: Generate
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-rust-${{ hashFiles('**/Cargo.toml') }}
    - id: configure-pages
      uses: actions/configure-pages@v3
    - run: cargo generate ${{steps.configure-pages.outputs.base_url}}
    - uses: browser-actions/setup-chrome@v1
    - uses: nanasess/setup-chromedriver@v2
    - run: |
        chromedriver --log-level=ALL --log-path=chromedriver.log &
        sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
    - run: cargo crawl
    - uses: actions/upload-artifact@v3
      with:
        name: site
        path: _site
  validate:
    needs:
    - generate
    name: Validate
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      with:
        name: site
        path: _site
    - run: pip install git+https://github.com/tommy-gilligan/html5validator.git
    - run: html5validator --root _site/ --also-check-css
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-rust-${{ hashFiles('**/Cargo.toml') }}
    - uses: browser-actions/setup-chrome@v1
    - uses: nanasess/setup-chromedriver@v2
    - run: |
        chromedriver --log-level=ALL --log-path=chromedriver.log &
        sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
    - run: cargo test -- browser_
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: validate-screenshots
        path: screenshots
  deploy:
    needs:
    - ci
    - validate
    - screenshot
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      with:
        name: site
        path: _site
    - uses: actions/upload-pages-artifact@v2
    - uses: actions/deploy-pages@v2
  screenshot:
    needs:
    - generate
    name: Screenshot
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      with:
        name: site
        path: _site
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-rust-${{ hashFiles('**/Cargo.toml') }}
    - uses: browser-actions/setup-chrome@v1
    - uses: nanasess/setup-chromedriver@v2
    - run: |
        chromedriver --log-level=ALL --log-path=chromedriver.log &
        sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
    - run: cargo screenshot
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: screenshots
        path: screenshots
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: chromedriver-log
        path: chromedriver.log
