name: CI

on: [push]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-D warnings"
  DISPLAY: ":99"
  RUST_BACKTRACE: 1

jobs:
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/.crates.toml
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            xtask/target
            generation/target
          key: ${{ runner.os }}-clippy-${{ hashFiles('**/Cargo.toml') }}
      - run: cargo clippy --all-targets
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/.crates.toml
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            xtask/target
            generation/target
          key: ${{ runner.os }}-format-${{ hashFiles('**/Cargo.toml') }}
      - run: cargo fmt --check
  generate:
    name: Generate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: dtolnay/rust-toolchain@nightly
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/.crates.toml
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            xtask/target
            generation/target
          key: ${{ runner.os }}-generate-${{ hashFiles('**/Cargo.toml') }}
      - id: configure-pages
        uses: actions/configure-pages@v3
      - run: cargo xtask generate --base-url ${{steps.configure-pages.outputs.base_url}}
      - run: cargo xtask crawl https://localhost/
      - uses: actions/upload-artifact@v3
        with:
          name: site
          path: _site
  browser:
    needs: [generate]
    name: Browser
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: site
          path: _site
      - uses: Cyb3r-Jak3/html5validator-action@v7.2.0
        with:
          css: true
          root: _site/
      - uses: dtolnay/rust-toolchain@nightly
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/.crates.toml
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            xtask/target
            generation/target
          key: ${{ runner.os }}-browser-${{ hashFiles('**/Cargo.toml') }}
      - uses: browser-actions/setup-chrome@v1
      - uses: nanasess/setup-chromedriver@v2
        with:
          chromedriver-version: '115.0.5790.102'
      - run: |
          chromedriver --verbose --enable-chrome-logs --log-path=chromedriver.log &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
  deploy:
    needs: [clippy, format, browser]
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: site
          path: _site
      - uses: actions/upload-pages-artifact@v2
      - uses: actions/deploy-pages@v2
