name: CI

on: [push]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-D warnings"
  DISPLAY: ":99"

jobs:
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/.crates.toml
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-clippy-${{ hashFiles('**/Cargo.toml') }}
      - run: cargo clippy --all-targets
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/.crates.toml
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-format-${{ hashFiles('**/Cargo.toml') }}
      - run: cargo fmt --check
  browser:
    name: Browser
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/.crates.toml
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-browser-${{ hashFiles('**/Cargo.toml') }}
      - run: cargo run
      - uses: Cyb3r-Jak3/html5validator-action@v7.2.0
        with:
          css: true
          root: _site/
      - uses: browser-actions/setup-chrome@v1
      - uses: nanasess/setup-chromedriver@v2
        with:
          chromedriver-version: '115.0.5790.102'
      - run: |
          chromedriver --verbose --enable-chrome-logs --log-path=chromedriver.log &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
      - run: cargo test
      - name: Chromedriver Log
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: chromedriver-log
          path: chromedriver.log
  build:
    needs: [clippy, format, browser]
    name: Build site and deploy
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/.crates.toml
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-build-${{ hashFiles('**/Cargo.toml') }}
      - run: cargo run
      - uses: actions/upload-pages-artifact@v2
      - uses: actions/deploy-pages@v2
