name: CI
on:
- push
concurrency:
  group: ${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}
  cancel-in-progress: true
env:
  CARGO_TERM_COLOR: always
  DISPLAY: :99
  RUST_BACKTRACE: 1
jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/.crates.toml
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-rust-${{ hashFiles('**/Cargo.toml') }}
    - run: cargo xtask ci
  generate:
    needs:
    - ci
    name: Generate
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/.crates.toml
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-rust-${{ hashFiles('**/Cargo.toml') }}
    - id: configure-pages
      uses: actions/configure-pages@v3
    - run: cargo generate --base-url ${{steps.configure-pages.outputs.base_url}}
    - run: cargo crawl --base-url ${{steps.configure-pages.outputs.base_url}}
    - uses: actions/upload-artifact@v3
      with:
        name: site
        path: _site
  browser:
    needs:
    - generate
    name: Browser
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      with:
        name: site
        path: _site
    - uses: Cyb3r-Jak3/html5validator-action@v7.2.0
      with:
        css: true
        root: _site/
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/.crates.toml
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-rust-${{ hashFiles('**/Cargo.toml') }}
    - uses: browser-actions/setup-chrome@v1
    - uses: nanasess/setup-chromedriver@v2
    - run: |
        chromedriver --verbose --enable-chrome-logs --log-path=chromedriver.log &
        sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
  deploy:
    needs:
    - ci
    - browser
    - screenshot
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      with:
        name: site
        path: _site
    - uses: actions/upload-pages-artifact@v2
    - uses: actions/deploy-pages@v2
  dependencies:
    name: Dependencies
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/.crates.toml
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-rust-${{ hashFiles('**/Cargo.toml') }}
    - run: cargo install cargo-udeps
    - run: cargo udeps
  screenshot:
    needs:
    - generate
    name: Screenshot
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      with:
        name: site
        path: _site
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/.crates.toml
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-rust-${{ hashFiles('**/Cargo.toml') }}
    - uses: browser-actions/setup-chrome@v1
    - uses: nanasess/setup-chromedriver@v2
    - run: |
        chromedriver --log-level=ALL --log-path=chromedriver.log &
        sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
    - run: cargo screenshot --base-url http://example.com
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: screenshots
        path: screenshots
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: chromedriver-log
        path: chromedriver.log`
