name: CI

on: [push]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-D warnings"
  ACTIONS_STEP_DEBUG: true
  ACTIONS_RUNNER_DEBUG: true
  DISPLAY: ":99"

jobs:
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/.crates.toml
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-clippy-${{ hashFiles('**/Cargo.toml') }}
      - run: cargo clippy --all-targets
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/.crates.toml
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-format-${{ hashFiles('**/Cargo.toml') }}
      - run: cargo fmt --check
  browser:
    name: Browser
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: browser-actions/setup-chrome@v1
      - uses: nanasess/setup-chromedriver@v2
      - run: |
          chromedriver --verbose --enable-chrome-logs &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/.crates.toml
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-browser-${{ hashFiles('**/Cargo.toml') }}
      - run: cargo run
      - run: cargo test
  build:
    needs: [clippy, format, browser]
    name: Build site and deploy
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/.crates.toml
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-build-${{ hashFiles('**/Cargo.toml') }}
      - run: cargo run
      - uses: actions/upload-pages-artifact@v2
      - uses: actions/deploy-pages@v2
