on:
  push:
    branches:
      - main

name: CI

jobs:
  build:
    permissions:
      pages: write
      id-token: write
    name: Build site and deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo run
      - uses: actions/upload-pages-artifact@v2
      - uses: actions/deploy-pages@v2
